spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/want-a-pet?createDatabaseIfNotExist=true
    username: root
    password: ${MYSQL_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: false
#mail:
#  host: localhost
#  port: 1025
#  username: "admin@example.com"
#  password: ""