spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/want-a-pet?createDatabaseIfNotExist=true
    username: root
    password: ${MYSQL_PASS}
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
    resources: # Static resources
      static-locations: file:src/main/resources/static/
      cache:
        period: 0
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: false

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE

  wantapet:
    default.admin.pass: ${DEFAULT_ADMIN_PASS:topsecret}
    remember.me.key: ${REMEMBER_ME_KEY:topsecret}

#cloudinary:
#  cloud-name: ${CLOUD_NAME}
#  api-key: ${API_KEY}
#  api-secret: %{API_SECRET}
#  main:
#    allow-circular-references: true
#mail:
#  host: localhost
#  port: 1025
#  username: "admin@example.com"
#  password: ""